version: '3.9'

services:
  elastic-enrich-reference:
    image: node:gallium-alpine
    networks:
      elastic_public:
    environment:
      - ES_HOSTS=analytics-datastore-elastic-search-01:9200,analytics-datastore-elastic-search-02:9200,analytics-datastore-elastic-search-03:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=dev_password_only
    deploy:
      resources:
        limits:
          memory: 2G
      restart_policy:
        condition: none
      placement:
        constraints:
          - "node.labels.name==node-1"
    command: sh -c "cd /app && npm run start && exit"
    volumes:
      - ../:/app

networks:
  elastic_public:
    name: elastic_public
    external: true
